#include    <stdio.h>
#include    <string.h>
#include    <stdlib.h>
#include    <unistd.h>
#include    <errno.h>
#include    <sys/stat.h>
#include    <fcntl.h>
#include    <mqueue.h>
#include	<sys/types.h>
#include	<sys/mman.h>
#include	<sys/shm.h>
#include	<sys/ipc.h>
