#include	<stdio.h>
#include	<fcntl.h>
#include	<sys/stat.h>
#include	<string.h>
#include	<linux/libc-compat.h>
#include	<unistd.h>
#include	<stdlib.h>
#include	<sys/types.h>  
#include	<sys/socket.h>
#include	<netinet/in.h>
#include	<netinet/ip.h>
//#include	<arpa/inet.h>
